### ISSUE TITLE
Allow single point coordinates in .get_timespan

### ISSUE THREAD

**Issue by dbrownf** [agrobioinfoservices/gosset#5]
The current version only allows to input geographic coordinates as bounding boxes and not as single point coordinates.

**Comment by kauedesousa** [comment]
`nasapower::get_power` indeed allows one single point, but this cannot be passed as a vector, requiring one call for each point. Making the call within a bbox should work for both cases (single points or multiple points). The function works for one single point, but the `lonlat` values should be an object of class `data.frame`


````
library("gosset")

lonlat <- data.frame(lon = runif(10, 11, 12),
                     lat = runif(10, 55, 58))

pdates <- as.integer(runif(10, 17666, 17670))
pdates <- as.Date(pdates, origin = "1970-01-01")

rainfall(lonlat[1,],
         day.one = pdates[1],
         span = 50)
````
